name: Generate API Files

on:
  push:
    branches: [ master ]
    paths:
      - 'wp/**'  # Trigger when files in the wp directory change
      - 'google-drive-mapping.json'  # Trigger when Google Drive mapping changes
      - 'config.js'  # Trigger when configuration changes
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Needed to push changes back to the repository

jobs:
  generate-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper commits

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check mapping file
      run: npm run check-mapping-file

    - name: Generate API files
      run: npm run generate-data

    - name: Update GitHub Pages files
      run: |
        # Copy index file
        cp github-pages-index.html index.html

        # Copy config file
        cp config.js config.js

        # Create js directory
        mkdir -p js

        # Copy js files
        cp -v js/github-pages-app.js js/

        # Create a simple proxy.js file (using echo with multiple lines)
        echo 'window.GoogleDriveProxy = {
          extractFileId: function(url) {
            if (url.includes("export=view&id=")) {
              const idParam = url.split("id=")[1];
              return idParam ? idParam.split("&")[0] : null;
            }
            const fileMatch = url.match(/\/file\/d\/([^/]+)/);
            if (fileMatch && fileMatch[1]) return fileMatch[1];
            const idMatch = url.match(/[?&]id=([^&]+)/);
            if (idMatch && idMatch[1]) return idMatch[1];
            return null;
          },
          loadImage: function(driveUrl) {
            return new Promise((resolve, reject) => {
              const fileId = this.extractFileId(driveUrl);
              if (!fileId) {
                reject(new Error("Invalid Google Drive URL"));
                return;
              }
              const thumbnailUrl = "https://drive.google.com/thumbnail?id=" + fileId + "&sz=w2000";
              console.log("Using Google Drive thumbnail API:", thumbnailUrl);
              resolve(thumbnailUrl);
            });
          }
        };' > js/proxy.js

        # List files to verify
        ls -la js/

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add api/ data/ index.html css/ js/ config.js google-drive-mapping.json

        # Determine commit message based on what triggered the workflow
        COMMIT_MSG="Auto-generate API files"
        if git diff --name-only HEAD | grep -q "google-drive-mapping.json"; then
          COMMIT_MSG="$COMMIT_MSG (Google Drive mapping updated)"
        elif git diff --name-only HEAD | grep -q "wp/"; then
          COMMIT_MSG="$COMMIT_MSG (new images added)"
        elif git diff --name-only HEAD | grep -q "config.js"; then
          COMMIT_MSG="$COMMIT_MSG (configuration updated)"
        fi

        git diff --quiet && git diff --staged --quiet || git commit -m "$COMMIT_MSG"
        git push
